# Generated by Django 4.0.4 on 2022-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_contact_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, default='unknown', max_length=200, null=True),
        ),
    ]
