# Generated by Django 4.0.4 on 2022-10-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
