# Generated by Django 4.0.4 on 2022-10-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_rename_friends_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=models.TextField(editable=False),
        ),
    ]
