# Generated by Django 4.0.4 on 2022-10-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_chat_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=models.TextField(),
        ),
    ]
