# Generated by Django 4.0.4 on 2022-10-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_chat_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
