# Generated by Django 4.0.4 on 2022-10-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_chat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='roomname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
