# Generated by Django 4.0.4 on 2022-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('img', 'image'), ('txt', 'text'), ('vid', 'video')], max_length=50),
        ),
    ]
