# Generated by Django 4.2.1 on 2023-05-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_remove_attendance_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
