# Generated by Django 4.2.1 on 2023-05-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_rename_sallary_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
        migrations.DeleteModel(
            name='salary',
        ),
    ]
